### ISSUE TITLE
Guide for Swift

### ISSUE THREAD

**Issue by VincentV89** [wirecard/paymentSDK-iOS#3]
Hi, is there a guide for swift on this?

**Comment by stefan-sedlak** [comment]
Hi @VincentV89,
we plan to release demo shop app. It is written in Swift :)
I will notice you when it will be publicly available.

**Comment by VincentV89** [comment]
Thanks for the notice.

By the way, i tried plainly importing the library and running my workable app as it is. It produces these errors. It seems like the library isnt supporting different architecture types. Could you advise on this please? Thanks.

<img width="980" alt="screen shot 2017-08-18 at 11 12 33 am" src="https://user-images.githubusercontent.com/17560003/29442783-64f199f6-8406-11e7-8b14-cc00b2dedfa2.png">

**Comment by stefan-sedlak** [comment]
Library contains all architectures.
`> $ file PaymentSDK`
PaymentSDK: Mach-O universal binary with 4 architectures: [arm_v7: current ar archive] [i386] [x86_64] [arm64]

The issue is that when you manually import framework you need to import dependencies listed in [podspec](https://github.com/wirecard/paymentSDK-iOS/blob/master/paymentSDK.podspec).
I advice to use Cocoapods.

**Comment by stefan-sedlak** [comment]
Small Swift example was provided here: https://github.com/wirecard/paymentSDK-iOS/tree/master/Example-Swift

Best,
Stefan
