### ISSUE TITLE
SKD is using advertisingIdentifier 

### ISSUE THREAD

**Issue by lukewar** [wirecard/paymentSDK-iOS#9]
By using paymentSDK iTunes Connect validation discovers usage of ASIdentifierManager API
https://developer.apple.com/documentation/adsupport/asidentifiermanager.

Is there a version of an SDK that does not use this API behind a scenes?

Used version 2.17.0. Resubmitting with 2.17.3, but `grep -r advertisingIdentifier .` still indicates that paymentSDK framework contains references.

```
$ grep -r advertisingIdentifier .
Binary file ./Pods/paymentSDK/PaymentSDK.framework/PaymentSDK matches
./Pods/paymentSDK/PaymentSDK.framework/Headers/WDPayPalPayment.h:@property (strong, nonatomic, nullable) NSString *advertisingIdentifier;
```

**Comment by stefan-sedlak** [comment]
Hi @lukewar ,
as you can see in WDPayPalPayment [class](https://github.com/wirecard/paymentSDK-iOS/blob/e441db3a465d0cebdeb774b0b8b5291e81b6123f/PaymentSDK.framework/Headers/WDPayPalPayment.h#L35) the property type is `NSString`. It just uses name `advertisingIdentifier`.

In previous releases paymentSDK was using AdSupport framework directly.
Since release [2.17.2](https://github.com/wirecard/paymentSDK-iOS/releases/tag/2.17.2) it is only NSString and it is up to your app if AdSupport framework and `ASIdentifierManager` class is used.
It is not used directly from paymentSDK. Usage is optional and up to your decision.
